import { app } from "../../scripts/app.js";

export const SETTING_IDS = {
    sidebarBrowserEnabled: "MetadataBooster.SidebarBrowser.Enabled",
    sidebarBrowserAutoGeneratedEnabled: "MetadataBooster.SidebarBrowser.AutoGenerated.Enabled",
    assetsPreviewEnabled: "MetadataBooster.AssetsPreview.Enabled",
    assetsPreviewFields: "MetadataBooster.AssetsPreview.Fields",
};

export const DEFAULT_HOVER_FIELDS =
    "filename,dimensions,format,model,loras,seed,steps,sampler,cfg,prompt";

const listeners = new Set();

const state = {
    sidebarBrowserEnabled: true,
    sidebarBrowserAutoGeneratedEnabled: true,
    assetsPreviewEnabled: true,
    assetsPreviewFields: [],
};

export function parseFieldList(value) {
    return Array.from(
        new Set(
            String(value ?? "")
                .split(",")
                .map((item) =>
                    item
                        .trim()
                        .toLowerCase()
                        .replace(/[^a-z0-9]+/g, "_")
                        .replace(/^_+|_+$/g, ""),
                )
                .filter(Boolean),
        ),
    );
}

function notifyListeners() {
    const snapshot = getSettingsState();
    for (const listener of listeners) {
        try {
            listener(snapshot);
        } catch (error) {
            console.error("[Metadata Booster] Failed to notify settings listener", error);
        }
    }
}

export function getSettingValue(id, fallback) {
    const extensionValue = app.extensionManager?.setting?.get?.(id);
    if (extensionValue !== undefined) {
        return extensionValue;
    }

    const uiValue = app.ui?.settings?.getSettingValue?.(id, fallback);
    return uiValue === undefined ? fallback : uiValue;
}

export function syncSettingsFromStore() {
    state.sidebarBrowserEnabled = Boolean(
        getSettingValue(SETTING_IDS.sidebarBrowserEnabled, true),
    );
    state.sidebarBrowserAutoGeneratedEnabled = Boolean(
        getSettingValue(SETTING_IDS.sidebarBrowserAutoGeneratedEnabled, true),
    );
    state.assetsPreviewEnabled = Boolean(
        getSettingValue(SETTING_IDS.assetsPreviewEnabled, true),
    );
    state.assetsPreviewFields = parseFieldList(
        getSettingValue(SETTING_IDS.assetsPreviewFields, DEFAULT_HOVER_FIELDS),
    );
    return getSettingsState();
}

export function getSettingsState() {
    return {
        sidebarBrowserEnabled: state.sidebarBrowserEnabled,
        sidebarBrowserAutoGeneratedEnabled: state.sidebarBrowserAutoGeneratedEnabled,
        assetsPreviewEnabled: state.assetsPreviewEnabled,
        assetsPreviewFields: [...state.assetsPreviewFields],
    };
}

export function subscribeSettings(listener) {
    listeners.add(listener);
    return () => listeners.delete(listener);
}

export const EXTENSION_SETTINGS = [
    {
        id: SETTING_IDS.sidebarBrowserEnabled,
        name: "Metadata Booster: Enable metadata browser sidebar",
        type: "boolean",
        defaultValue: true,
        category: ["Metadata Booster", "Sidebar browser"],
        tooltip:
            "Show the Metadata Browser tab in the sidebar for dropped local image and video files.",
        onChange(value) {
            state.sidebarBrowserEnabled = Boolean(value);
            notifyListeners();
        },
    },
    {
        id: SETTING_IDS.sidebarBrowserAutoGeneratedEnabled,
        name: "Metadata Booster: Auto-load generated media in metadata browser",
        type: "boolean",
        defaultValue: true,
        category: ["Metadata Booster", "Sidebar browser"],
        tooltip:
            "Automatically add current ComfyUI node preview images and videos to the Metadata Browser while workflows are running.",
        onChange(value) {
            state.sidebarBrowserAutoGeneratedEnabled = Boolean(value);
            notifyListeners();
        },
    },
    {
        id: SETTING_IDS.assetsPreviewEnabled,
        name: "Metadata Booster: Enable Assets/media metadata preview",
        type: "boolean",
        defaultValue: true,
        category: ["Metadata Booster", "Hover preview"],
        tooltip:
            "Show a lightweight metadata tooltip when hovering or focusing Assets/media cards.",
        onChange(value) {
            state.assetsPreviewEnabled = Boolean(value);
            notifyListeners();
        },
    },
    {
        id: SETTING_IDS.assetsPreviewFields,
        name: "Metadata Booster: Assets/media preview fields",
        type: "text",
        defaultValue: DEFAULT_HOVER_FIELDS,
        category: ["Metadata Booster", "Hover preview"],
        tooltip:
            "Comma-separated preview fields. Available keys include filename, dimensions, format, model, loras, seed, steps, sampler, scheduler, cfg, codec, duration, prompt, and negative_prompt.",
        attrs: {
            style: {
                fontFamily: "monospace",
            },
        },
        onChange(value) {
            state.assetsPreviewFields = parseFieldList(value);
            notifyListeners();
        },
    },
];
